tclmode

# Generated by Genus(TM) Synthesis Solution 20.10-p001_1, revision 1.483b2
# Generated on: Wed Feb 11 10:20:59 CST 2026 (Wed Feb 11 02:20:59 UTC 2026)

set_screen_display -noprogress
set_dofile_abort exit

### Alias mapping flow is enabled. ###
# Root attribute 'wlec_rtl_name_mapping_flow' was 'false'.
# Root attribute 'alias_flow'                 was 'true'.

set lec_version [regsub {(-)[A-Za-z]} $env(LEC_VERSION) ""]

# Turns on the flowgraph datapath solver.
set wlec_analyze_dp_flowgraph true
# Indicates that resource sharing datapath optimization is present.
set share_dp_analysis         true

# The flowgraph solver is recommended for datapath analysis in LEC 19.1 or newer.
set lec_version_required "19.10100"
if {$lec_version >= $lec_version_required &&
    $wlec_analyze_dp_flowgraph} {
    set DATAPATH_SOLVER_OPTION "-flowgraph"
} elseif {$share_dp_analysis} {
    set DATAPATH_SOLVER_OPTION "-share"
} else {
    set DATAPATH_SOLVER_OPTION ""
}

tcl_set_command_name_echo on

set_log_file ./g2p.lec.log -replace

usage -auto -elapse

set_verification_information dig_top_synv_dig_topvgz_db

read_implementation_information fv/dig_top -golden dig_top_synv -revised dig_topvgz

# Root attribute 'wlec_multithread_license_list' can be used to specify a license list
# for multithreaded processing. The default list is used otherwise.
set_parallel_option -threads 1,16 -norelease_license
set_compare_options -threads 1,16

set env(RC_VERSION)     "20.10-p001_1"
set env(CDN_SYNTH_ROOT) "/home/cad/EDA/tools/Cadence/GENUS_20.1/tools.lnx86"
set CDN_SYNTH_ROOT      "/home/cad/EDA/tools/Cadence/GENUS_20.1/tools.lnx86"
set env(CW_DIR) "/home/cad/EDA/tools/Cadence/GENUS_20.1/tools.lnx86/lib/chipware"
set CW_DIR      "/home/cad/EDA/tools/Cadence/GENUS_20.1/tools.lnx86/lib/chipware"

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

add_search_path . /home/cad/EDA/tools/Cadence/GENUS_20.1/tools.lnx86/lib/tech -library -both
read_library -liberty -both /mnt/hgfs/project/MI2519/model/Lib/smic/1.2v/scc018ug_uhd_rvt_ss_v1p08_125c_basic.lib /mnt/hgfs/project/MI2519/model/Lib/smic/1.8v/scc018ug_uhd_rvt_ff_v1p98_-40c_basic.lib

read_design -verilog95   -golden -lastmod -noelab ../../../impl/APR/eco/dig_top_sim.v.pre.v
elaborate_design -golden -root {dig_top}

read_design -verilog95   -revised -lastmod -noelab ../../../impl/APR/eco/dig_top_sim.eco617.v
elaborate_design -revised -root {dig_top}

#add_name_alias fv/dig_top/dig_top_synv.singlebit.original_name.alias.json.gz -golden
#set_mapping_method -alias -golden

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge
set_flatten_model -gated_clock

#add_name_alias fv/dig_top/dig_topvgz.singlebit.original_name.alias.json.gz -revised
#set_mapping_method -alias -revised
#add_renaming_rule r1alias _reg(%w?(/U\\\$%d)*)$ @1 -type dff dlat -both

# Reports the quality of the implementation information.
# This command is only available with LEC 20.10-p100 or later.
set lec_version_required "20.10100"
if {$lec_version >= $lec_version_required} {
    check_verification_information
}

set_analyze_option -auto -report_map

set_system_mode lec
report_unmapped_points -summary
report_unmapped_points -notmapped
add_compared_points -all
compare

report_compare_data -class nonequivalent -class abort -class notcompared
report_verification -verbose
report_statistics

write_verification_information
report_verification_information

# Reports how effective the implementation information was.
# This command is only available with LEC 18.20-d330 or later.
set lec_version_required "18.20330"
if {$lec_version >= $lec_version_required} {
    report_implementation_information
}

puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}

# Generate a detailed summary of the run.
# This command is available with LEC 19.10-p100 or later.
set lec_version_required "19.10100"
if {$lec_version >= $lec_version_required} {
analyze_results -logfiles ./g2p.lec.log
}

vpxmode

exit -f
